# 是否启用Fancybox图片灯箱效果
# Disqus评论 shortnam：tianci
disqus: 

# 友言评论 id
uyan: 
# 来必力评论 data-uid
livere: 
# 畅言评论 appid
changyan: 
# 
changyan_conf: ## Your changyan conf, e.g. prod_d8a508c2825ab57eeb43e7c69bba0e8b
# Gitment评论相关参数
gitment:
  enable: false
  owner: 
  repo: 
  client_id: 
  client_secret: 
# Gitalk评论相关参数
gitalk:
  enable: false 
  owner:  
  repo: 
  client_id:  
  client_secret:  
  admin:  
# Valine评论相关参数 npm install valine --save
# https://valine.js.org/
valine: 
  # 是否开启
  enable: true
  # AppID
  appid: NjsQAuL1k29JMFf121E0AJHF-gzGzoHsz
  # AppKey
  appkey: 7zPSYnuDLeyCNoSQpgTXdC1v
  # 评论系统中的邮件提醒设置 https://github.com/xCss/Valine/wiki
  notify: true 
  # 是否需要验证，验证比较反人类建议false关闭
  verify: false
  # 默认留言框内的文字
  placeholder: 
  # 默认头像
  avatar: 'mm' 
  # pagination size #默认单页的留言条数
  pageSize: 10
  # 默认留言框的头部需要访问者输入的信息 nick,mail,link
  guest_info: nick,mail,link
  
# 默认使用Google搜索引擎
google_search: false
# 若想使用百度搜索，将其设定为 true
baidu_search: false
# Swiftype 站内搜索key
swiftype: 
# 微搜索 key
tinysou: 
# 基于jQuery的本地搜索引擎，需要安装hexo-generator-search插件使用
self_search: true
# Google Analytics 跟踪ID
google_analytics: 
# 百度统计 跟踪ID
baidu_analytics: 
# 
fancybox: true ## If you want to use fancybox please set the value to true.
# 是否显示侧边栏分类数目
show_category_count: true
# 是否显示文章中目录列表自动编号
toc_number: true
#  是否使用分享按鈕，需要安装hexo-helper-qrcode插件使用
shareto: true
#  是否使用不蒜子页面访问计数
busuanzi: true
# 文章计数器、预计阅读时间 需安装：hexo-wordcount
wordcount: true
# 是否在移动设备屏幕底部显示侧边栏
widgets_on_small_screens: false
# 是否使用canvas动态背景
canvas_nest:
  enable: false
  color: ## RGB value of the color, e.g. "100,99,98"
  opacity: ## Transparency of lines, e.g. "0.7"
  zIndex: ## The z-index property of the background, e.g. "-1"
  count: ## Quantity of lines, e.g. "150"
# 是否启用捐赠按钮
donate:
  enable: false
  github: ## GitHub URL, e.g. https://github.com/Kaiyuan/donate-page
  alipay_qr: ## Path of Alipay QRcode image, e.g. /img/AliPayQR.png
  wechat_qr: ## Path of Wechat QRcode image, e.g. /img/WeChatQR.png
  btc_qr: ## Path of Bitcoin QRcode image, e.g. /img/BTCQR.png
  btc_key: ## Bitcoin key, e.g. 1KuK5eK2BLsqpsFVXXSBG5wbSAwZVadt6L
  paypal_url: ## Paypal URL, e.g. https://www.paypal.me/tufu9441
# 
post_copyright:
  enable: false ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: ## Your author name, e.g. tufu9441
  copyright_text: ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.

# 自定义页面及菜单，依照已有格式填写。
# 填写后请在source目录下建立相应名称的文件夹，并包含index.md文件，以正确显示页面。
# 导航菜单中集成了FontAwesome图标字体，可以在这里选择新的图标，并按照相关说明使用。
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: history
    directory: history/
    icon: fa-history
  - page: rss
    directory: atom.xml
    icon: fa-rss

# 选择和排列希望使用的侧边栏小工具
# Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
widgets: 
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

# 友情链接，请依照格式填写
links:
  - title: 博主CSDN
    url: https://blog.csdn.net/tian_ci/
#  - title: site-name2
#    url: http://www.example2.com/
#  - title: site-name3
#    url: http://www.example3.com/

# 网站历史时间线，在页面front-matter中设置layout: timeline可显示
timeline:
  - num: 2
    word: 2019/05/20-在博客瘫痪进4个月后重构博客
  - num: 1
    word: 2018/11/28-接触Hexo搭建个人博客

# Static files
# 静态文件存储路径，方便设置CDN缓存
js: js
css: css

# Theme version
# 主题版本，便于静态文件更新后刷新CDN缓存
version: 1.0.0

# 页脚配置
footer: 
  # 建站年份
  since: 2018